package com.sachini.emmamemorygame

import androidx.compose.ui.graphics.Color

object AppColors {
    val background   = Color(0xFFFFF8F0)
    val xpBg         = Color(0xFFFAEEDA)
    val xpFill       = Color(0xFFD85A30)
    val xpTrack      = Color(0xFFF5C4B3)
    val xpText       = Color(0xFF633806)
    val xpSub        = Color(0xFF854F0B)
    val timerBg      = Color(0xFFE1F5EE)
    val timerFill    = Color(0xFF1D9E75)
    val timerTrack   = Color(0xFF9FE1CB)
    val emmaMsgBg    = Color(0xFFFBEAF0)
    val emmaMsgText  = Color(0xFF72243E)
    val memoryBg     = Color(0xFFE8F5E9)
    val memoryText   = Color(0xFF27500A)
    val reactionBg   = Color(0xFFE6F1FB)
    val reactionText = Color(0xFF0C447C)
    val skillBarHigh = Color(0xFF1D9E75)
    val skillBarLow  = Color(0xFF9FE1CB)
    val orange       = Color(0xFFD85A30)
    val green        = Color(0xFF1D9E75)
    val purple       = Color(0xFF534AB7)
    val streakBg     = Color(0xFFFFF3E0)
    val streakText   = Color(0xFFE65100)
    val goldBg       = Color(0xFFFFF8E1)
    val goldText     = Color(0xFFFF8F00)
    val shieldHidden    = Color(0xFF0F6E56)
    val shieldBorder    = Color(0xFF085041)
    val shieldInner     = Color(0xFF1D9E75)
    val shieldText      = Color(0xFF9FE1CB)
    val shieldRevealed  = Color(0xFFFAEEDA)
    val shieldRevBorder = Color(0xFFEF9F27)
    val shieldMatched   = Color(0xFFE1F5EE)
    val shieldMatBorder = Color(0xFF1D9E75)
    val shieldSymColor  = Color(0xFF633806)
    val shieldMatColor  = Color(0xFF0F6E56)
}
